import z from "zod";

export const ssbuCharacters = [
	"Banjo & Kazooie",
	"Bayonetta",
	"Bowser",
	"Bowser Jr",
	"Byleth",
	"Captain Falcon",
	"Chrom",
	"Cloud",
	"Corrin",
	"Daisy",
	"Dark Pit",
	"Dark Samus",
	"Diddy Kong",
	"Donkey Kong",
	"Dr. Mario",
	"Duck Hunt",
	"Falco",
	"Fox",
	"Ganondorf",
	"Greninja",
	"Hero",
	"Ice Climbers",
	"Ike",
	"Incineroar",
	"Inkling",
	"Isabelle",
	"Jigglypuff",
	"Joker",
	"Kazuya",
	"Ken",
	"King Dedede",
	"King K. Rool",
	"Kirby",
	"Link",
	"Little Mac",
	"Lucario",
	"Lucas",
	"Lucina",
	"Luigi",
	"Mario",
	"Marth",
	"Mega Man",
	"Meta Knight",
	"Mewtwo",
	"Mii Fighter",
	"Min Min",
	"Mr. Game & Watch",
	"Ness",
	"Olimar",
	"Pac-Man",
	"Palutena",
	"Peach",
	"Pichu",
	"Pikachu",
	"Piranha Plant",
	"Pit",
	"Pokemon Trainer",
	"Pyra + Mythra",
	"Richter",
	"Ridley",
	"R.O.B",
	"Robin",
	"Rosalina & Luma",
	"Roy",
	"Ryu",
	"Samus",
	"Sephiroth",
	"Sheik",
	"Shulk",
	"Simon",
	"Snake",
	"Sonic",
	"Sora",
	"Steve",
	"Terry",
	"Toon Link",
	"Villager",
	"Wario",
	"Wii Fit Trainer",
	"Wolf",
	"Yoshi",
	"Young Link",
	"Zelda",
	"Zero Suit Samus",
] as const;

export const ssbuCharacterSchema = z.enum(ssbuCharacters);

export type SSBUCharacter = z.infer<typeof ssbuCharacterSchema>;
